name: Reconstrução do Projeto (Debian)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: debian:bookworm-slim

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Instalar dependências
        run: npm install

      - name: Corrigir package.json do web-server
        run: |
          sed -i /"test":/a   "build": "echo \"No build required\"", packages/web-server/package.json
          sed -i s/1"/1",/ packages/web-server/package.json

      - name: Executar Preflight (Build, Test, Lint)
        run: npm run preflight
