name: Reconstrução do Projeto (Debian)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: debian:bookworm-slim

    steps:
      - name: Instalar dependências do sistema
        run: |
          apt-get update
          apt-get install -y git jq

      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Corrigir package.json do web-server
        run: |
          mkdir -p packages/web-server
          echo "{\"name\": \"web-server\",\"version\": \"1.0.0\",\"main\": \"index.js\",\"scripts\": {\"test\": \"echo \\\"Error: no test specified\\\" && exit 1\",\"build\": \"echo \\\"No build required\\\"\"},\"keywords\": [],\"author\": \"\",\"license\": \"ISC\",\"description\": \"\"}" > packages/web-server/package.json

      - name: Instalar dependências do Node
        run: npm install

      - name: Executar Preflight (Build, Test, Lint)
        run: npm run preflight
